### ISSUE TITLE
Apex tests trigger automatically failed with unknow error ...

### ISSUE THREAD

**Issue by adarsha45** [dxatscale/sfpowerscripts#1407] opened 2023-09-13 06:26 UTC
i am currently using the code sfpowerscripts apextests:trigger -l RunApexTestSuite to run apextestsuite parallely 
but it keeps on automatically throwing errors and killing the process in uncertain manner. sometimes it is success and sometime not ,and not rerunning after the failure again .
the errors throws are : 
---------------------------------
Error: Cannot read properties of undefined (reading 'Status')
No test report files were found. Configuration error?
-------------------------------------
another error : 
System.DmlException: Insert failed. First exception on row 0; first error: UNKNOWN_EXCEPTION, common.udd.object.DmlOperationException: []
------------------------------------------------------------------------
FYI: it is not related to test failure.

**Comment by azlam-abdulsalam** [comment] 2023-09-14 11:26
Closing this as a duplicate of #1408

**Closed as completed by azlam-abdulsalam** 2023-09-14 11:26 UTC
Labels: analysis
